version: '3'
services:
  app:
    container_name: app
    build: .
    restart: always
    volumes:
      - ./:/var/www/
    depends_on:
      - db
      - redis
    networks: 
      - network-app

  db:
    image: mysql:5.7
    restart: always
    command: --innodb-use-native-aio=0
    container_name: db
    tty:  true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
    - "./.docker/dbdata:/var/lib/mysql"
    networks: 
      - network-app

  nginx:
    build: ./.docker/nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    networks: 
      - network-app
    depends_on:
      - app

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks: 
      - network-app
networks: 
  network-app:
    driver: bridge
